# Generated by Django 3.2.7 on 2021-09-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210909_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое название'),
        ),
    ]
