# Generated by Django 3.2.7 on 2021-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detailsUrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Путь к json-описанию'),
        ),
    ]
