# Generated by Django 3.2.7 on 2021-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_detailsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detailsUrl',
            field=models.FilePathField(blank=True, max_length=200, verbose_name='Путь к json-описанию'),
        ),
    ]
