# Generated by Django 3.2.7 on 2021-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_detailsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details',
            field=models.FileField(null=True, upload_to='', verbose_name='json-описание'),
        ),
    ]
