# Generated by Django 3.2.7 on 2021-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='detailsUrl',
        ),
        migrations.AlterField(
            model_name='place',
            name='details',
            field=models.FileField(null=True, upload_to='media', verbose_name='json-описание'),
        ),
    ]
