# Generated by Django 3.2.7 on 2021-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20210914_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='place',
            name='details',
            field=models.FileField(null=True, upload_to='', verbose_name='json-описание'),
        ),
    ]
