# Generated by Django 3.2.7 on 2021-09-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20210915_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
    ]
